/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/AgSd0A7cotz
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"

export function CreateButton({ onClick }) {
  return (
    <div className="flex justify-end w-full"> {/* Contenedor con justificación al final */}
      <Button className="flex items-center gap-2" variant="outline" onClick={onClick}>
        <PlusIcon className="w-4 h-4" /> <span className="">Agregar dispositivo </span>
      </Button>
    </div>
  );
}

function PlusIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>)
  );
}
