/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/j1jFDS7TKuL
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function CreateItem() {
  return (
    (<section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container px-4 md:px-6">
        <div className="space-y-6">
          <div className="space-y-2">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Crear nuevo dispositivo</h2>
            <p
              className="max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Registra un nuevo dispositivo en nuestro sistema para comenzar a monitorear su actividad y rendimiento.
            </p>
          </div>
          <form className="w-full max-w-md">
            <div className="grid gap-4">
              <div className="flex flex-col space-y-1.5">
                <Label htmlFor="store">Tienda</Label>
                <Select>
                  <SelectTrigger id="store">
                    <SelectValue placeholder="Selecciona una tienda" />
                  </SelectTrigger>
                  <SelectContent position="popper">
                    <SelectItem value="store1">Tienda Central</SelectItem>
                    <SelectItem value="store2">Tienda Norte</SelectItem>
                    <SelectItem value="store3">Tienda Sur</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="flex flex-col space-y-1.5">
                <Label htmlFor="serial">Número de serie</Label>
                <Input id="serial" placeholder="Ingresa el número de serie" />
              </div>
            </div>
            <Button className="mt-4" type="submit">
              Registrar dispositivo
            </Button>
          </form>
        </div>
      </div>
    </section>)
  );
}
