/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/8iDXR7grEIl
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"

export function DataViewToggle({ view, setView }) {
  return (
    <div className="flex items-center justify-center gap-4">
    <Button
      className={`px-6 py-2 rounded-md font-medium transition-colors ${view === 'hour' ? 'bg-gray-200 dark:bg-gray-700' : 'bg-gray-100 dark:bg-gray-800'} dark:text-gray-50`}
      variant="outline"
      onClick={() => setView('hour')}
    >
      Hora
    </Button>
    <Button
      className={`px-6 py-2 rounded-md font-medium transition-colors ${view === 'day' ? 'bg-gray-200 dark:bg-gray-700' : 'bg-gray-100 dark:bg-gray-800'} dark:text-gray-50`}
      variant="outline"
      onClick={() => setView('day')}
    >
      Día
    </Button>
    <Button
      className={`px-6 py-2 rounded-md font-medium transition-colors ${view === 'week' ? 'bg-gray-200 dark:bg-gray-700' : 'bg-gray-100 dark:bg-gray-800'} dark:text-gray-50`}
      variant="outline"
      onClick={() => setView('week')}
    >
      Semana
    </Button>
  </div>
  );
}
