/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/XsObB3lPwKc
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"

export function Loading() {
  return (
    <div className="flex  justify-center"> {/* Esta línea asegura el centrado completo */}
    <Card className="max-w-md">
      <CardHeader>
        <CardTitle>Cargando...</CardTitle>
        <CardDescription>Por favor, espere mientras obtenemos sus datos.</CardDescription>
      </CardHeader>
      <CardContent className="flex items-center justify-center" />
    </Card>
  </div>
  );
}
